name: satua
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  get: 4.6.6
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  flutter_gemini: ^2.0.3
  get_cli: ^1.8.1
  dcli: ^0.50.2

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - assets/images/

