name: satua
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.0
  cupertino_icons: ^1.0.6
  dcli: ^0.50.2
  device_preview: ^1.1.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_gemini: ^2.0.3
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.6
  get: 4.6.6
  get_cli: ^1.8.1
  lottie: ^3.1.0
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
