// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wIztSLvl5qxGBet5HbCO1gk3OhAlqgw',
    appId: '1:422438445111:web:fc8f2f4bb028fd79579fb2',
    messagingSenderId: '422438445111',
    projectId: 'satua-app',
    authDomain: 'satua-app.firebaseapp.com',
    storageBucket: 'satua-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0_OVKm9-No3ypgROwly9Rcd8bjKcUSM',
    appId: '1:422438445111:android:4918edb3198ce0e7579fb2',
    messagingSenderId: '422438445111',
    projectId: 'satua-app',
    storageBucket: 'satua-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwa-SojaDeE2vUoZPau9fJUAXrrPv6IA',
    appId: '1:422438445111:ios:f200654138fe96fb579fb2',
    messagingSenderId: '422438445111',
    projectId: 'satua-app',
    storageBucket: 'satua-app.appspot.com',
    iosBundleId: 'com.example.satua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuwa-SojaDeE2vUoZPau9fJUAXrrPv6IA',
    appId: '1:422438445111:ios:f200654138fe96fb579fb2',
    messagingSenderId: '422438445111',
    projectId: 'satua-app',
    storageBucket: 'satua-app.appspot.com',
    iosBundleId: 'com.example.satua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5wIztSLvl5qxGBet5HbCO1gk3OhAlqgw',
    appId: '1:422438445111:web:ba7edebf520c73dc579fb2',
    messagingSenderId: '422438445111',
    projectId: 'satua-app',
    authDomain: 'satua-app.firebaseapp.com',
    storageBucket: 'satua-app.appspot.com',
  );
}
